name: arcon

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  step_progress_indicator: ^1.0.2
  qr_flutter: ^4.1.0
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.1
  flutter_spinkit: ^5.2.0
  shimmer_animation: ^2.1.0+1
  url_strategy: ^0.2.0
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  image_picker_web: ^3.1.1
  mime_type: ^1.0.0
  url_launcher: ^6.1.14
  screenshot: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: TomatoGrotesk
      fonts:
        - asset: assets/fonts/TomatoGrotesk-Regular.otf
    - family: TomatoGroteskBold
      fonts:
        - asset: assets/fonts/TomatoGrotesk-ExtraBold.otf